name: Deploy
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        needs: Get code
        run: npm ci
      - name: Lint
        needs: Install dependencies
        run:
          npm run lint
      - name: Run tests
        needs: Lint
        run: npm run test
      - name: Build project
        needs: Run tests
        run: npm run build
      - name: Deploy
        needs: Run tests
        run: echo "Deploying ..." #just for showing what process may look like