name: Deploy
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: InstallNodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run:
          yarn run
          eslint --ext .jsx --fix src
      - name: Run tests
        run: vitest run
      - name: Get code
        uses: actions/checkout@v4
      - name: InstallNodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build project
        run: vite build
      - name: Deploy
        run: echo "Deploying ..." #just for showing what process may look like